### ISSUE TITLE
HYPRE 2.11.x does not compile with Visual Studio 2005

### ISSUE THREAD

**Issue by janusw** [LLNL/hypre#12]
Dear HYPRE team,

when compiling HYPRE 2.11.x with Visual Studio 2005, I see several errors. In particular this (admittedly quite old) compiler does not seem to like the inline declarations of functions like 'hypre_compare_and_swap' in line 105 of hypre_hopscotch_hash.h.

The 2.10.x versions of HYPRE used to work fine with VS2005, but unfortunately I cannot find any information on supported compiler versions. If there is such information, it would be great if anyone could throw me a quick pointer. If not, I think it might be very useful to add this information (e.g. in the INSTALL file or on a website), so that people know which versions of VS/gcc/clang are required to compile HYPRE and obtain correct results with it.

Best regards,
Janus

**Comment by rfalgout** [comment]
Hi Janus,

Thanks for letting us know about this problem.  Currently hypre requires a compiler that supports the ISO C99 standard (because of the 'static inline' stuff, among other things), though I'm not sure that's the issue with VS2005.  Unfortunately, we currently don't have a way to test VS, but we are actively working on resolving that issue.  Once that happens, we'll take a closer look.

Thanks again!

-Rob

**Comment by janusw** [comment]
Hi Rob,

thanks for your comments!

> Currently hypre requires a compiler that supports the ISO C99 standard (because of the 'static inline' stuff, among other things), though I'm not sure that's the issue with VS2005.

Apparently VS2005 does not fully support C99. I think that might indeed be issue.

However, looking into HYPRE's CMakeLists.txt, I see the following block:

```
if (MSVC)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)
  # Use the C++ compiler to compile these files to get around lack of C99 support
  set_source_files_properties (utilities/hypre_hopscotch_hash.c PROPERTIES COMPILE_FLAGS /TP)
  [...]
endif ()
```

This sounds a lot like a workaround to the problems I'm seeing (but if so, then it does not seem to work with VS2005). It looks like all the .c files that #include hypre_hopscotch_hash.h are listed there, but not the header itself (which should be interpreted as C++, if it's included from a file that is compiled with the C++ compiler, right?).

> Unfortunately, we currently don't have a way to test VS, but we are actively working on resolving that issue. Once that happens, we'll take a closer look.

In the meantime: If you have any ideas for a fix, I'll be happy to test ...

Thanks again!

Cheers,
Janus

**Comment by janusw** [comment]
I just noticed that there is also a comment about this issue in hypre_hopscotch_hash.h:

```
/******************************************************************************
 * This next section of code is here instead of in _hypre_utilities.h to get
 * around some portability issues with Visual Studio.  By putting it here, we
 * can explicitly include this '.h' file in a few files in hypre and compile
 * them with C++ instead of C (VS does not support C99 'inline').
 ******************************************************************************/
```

Not sure why that does not seem to work for me with VS2005 (using 'static inline' in a pure C++ project apparently works). Unfortunately I'm not able to test with a later VS version at present.

Cheers,
Janus

**Comment by rfalgout** [comment]
Hi Janus,

It looks like I am actually the one who made those changes, but I clearly forgot all about it. :)

It appears that VS2005 does support the 'inline' keyword, so I'm not sure what's going on here.  What exactly is the error message you are getting?

-Rob

**Comment by janusw** [comment]
Hi Rob,

> What exactly is the error message you are getting?

so, here's what I do ...

I'm on Win7 with VS2005. I check out the tag "v2.11.0" from github (which is the first released version that I see failing) . Then I use cmake 3.8.2 to generate VS project files (with the generator "Visual Studio 8 2005 Win64"). Just noticed that this already shows a little error (although configure runs through):

```
The C compiler identification is MSVC 14.0.50727
The CXX compiler identification is MSVC 14.0.50727
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 8/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 8/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 8/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 8/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - failed
Found MPI_C: C:/Program Files (x86)/Microsoft SDKs/MPI/lib/x64/msmpi.lib  
Found MPI_CXX: C:/Program Files (x86)/Microsoft SDKs/MPI/lib/x64/msmpi.lib  
Configuring done
```

Is "Detecting CXX compile features - failed" something to worry about here? Unfortunately it does not say which features it is missing. Anyway the project files are generated, so I open them with VS and start to build HYPRE with config "x64, Release". The first errors I see are:

```
1>Kompilieren...
1>par_strength.c
1>D:\DEV\SOURCE\hypre\hypre\src\utilities\hypre_hopscotch_hash.h(105) : error C2054: Nach 'inline' muss '(' folgen
1>D:\DEV\SOURCE\hypre\hypre\src\utilities\hypre_hopscotch_hash.h(106) : error C2085: 'hypre_compare_and_swap': Nicht in der formalen Parameterliste enthalten
1>D:\DEV\SOURCE\hypre\hypre\src\utilities\hypre_hopscotch_hash.h(106) : error C2143: Syntaxfehler: Es fehlt ';' vor '{'
```

I'm sorry about my VS speaking German. In English the first one is:

```
C2054: expected '(' to follow 'inline'
```

Any ideas or suggestions?

Thanks a bunch,
Janus

**Comment by janusw** [comment]
Some progress ...

Looking into the properties of the generated VS project file, I found the following:
* The global properties of the project 'HYPRE' (in Properties -> C/C++ -> Advanced) indicate that files should be compiled as C++ (/TP).
* However, the file-specific properties of all .c files (including hype_hopscotch_hash.c etc) indicate that they should all be compiled as C (/TC), apparently overriding the project-wide default.

This means that the cmake config lines like ...
```
  set_source_files_properties (utilities/hypre_hopscotch_hash.c PROPERTIES COMPILE_FLAGS /TP)
```
... seem to have no effect.

In fact I checked that setting /TP manually for those files makes HYPRE compile with VS2005. So we do have a workaround at least. Yay!  :smiley:

AFAICS the cause of this could be either
* a problem/error in the HYPRE's CMakeFiles.txt
* a bug in cmake (in combination with VS, possibly 2005 only?)
* related to my cmake config error (see above; how do I debug that?)

Would be great to hear from others whether HYPRE 2.11 works with later VS versions (2008 - 2017) or different cmake versions ...

Cheers,
Janus

**Comment by janusw** [comment]
One more data point: It seems that setting the COMPILE_FLAGS property on a file-by-file basis in principle works well, at least for this case:

```
# Turn optimization off for this file
if (MSVC)
  set_source_files_properties (lapack/dlamch.c PROPERTIES COMPILE_FLAGS /Od)
else ()
```

In contrast to other files, dlamch.c actually has the /Od flag in Release mode (in Debug mode, they all do).

Directly looking at the generated HYPRE.vcproj with an editor, I see:
```
			<File
				RelativePath="D:\DEV\SOURCE\hypre\hypre\src\lapack\dlamch.c">
				<FileConfiguration
					Name="Release|x64">
					<Tool
					Name="VCCLCompilerTool"
					CompileAs="1"
					Optimization="0"
					/>
```

And:
```
			<File
				RelativePath="D:\DEV\SOURCE\hypre\hypre\src\utilities\hypre_hopscotch_hash.c">
				<FileConfiguration
					Name="Release|x64">
					<Tool
					Name="VCCLCompilerTool"
					CompileAs="1"
					/>
```

If I set /TP via the IDE, "CompileAs" changes its value to "2".

Overall this indeed looks like a cmake bug to me. I guess I better report it to the cmake folks ...

Cheers,
Janus

**Comment by janusw** [comment]
> Overall this indeed looks like a cmake bug to me. I guess I better report it to the cmake folks ...

It may well be a cmake bug, but I actually found a nice way to make it work properly:

https://github.com/janusw/hypre/commit/9a140a43051b6913de51c8c93688f89cf827e2f5

**Comment by janusw** [comment]
Note: I finally found a way to test VS2015 on Windows 10, and fortunately it does not seem to be affected by this problem. v2.11.0 compiles fine (but only in Debug mode; Release mode fails due to issue #7).

**Comment by rfalgout** [comment]
Closing, since this does not seem to be an issue with later versions of VS and hypre 2.13.0
