### ISSUE TITLE
building HYPRE 2.12.0 with Visual Studio 2015: _Pragma undefined

### ISSUE THREAD

**Issue by janusw** [LLNL/hypre#16]
After fixing the issues with v2.11 and VS 2015 (see #14), I tried v2.12 and found an additional problem:
```
hypre\src\struct_mv\struct_innerprod.c(75): warning C4013: "_Pragma" undefiniert
```

Apparently _Pragma is a C99 operator, but not supported by VS so far. Instead, VS has its own version of it called __pragma (double underscore):

https://stackoverflow.com/questions/4782049/pragma-preprocessor-operator-in-visual-c

I wonder why MS is so ignorant of C99 ...

Cheers,
Janus

**Comment by rfalgout** [comment]
VS 2015 issues were resolved in version 2.13.0
