### ISSUE TITLE
Small bug in hypre_BoomerAMGBuildCoarseOperator?

### ISSUE THREAD

**Issue by IdoAkkerman** [LLNL/hypre#18]
Hello,

I am using MFEM the higher order finite element library also developed at LLNL. If I understand correctly MFEM uses the hypre_BoomerAMGBuildCoarseOperator routine to wrap MPI local matrices local to get the correct parallel representation.  

In my situation I have a mixed finite element spaces, meaning the RT matrix is not related to the P matrix, however they can have the same global size. In line 422/423 of the par_rap.c file there is a squareness check. Given that the global size is the same the routine assumes the problem is "square"( which is correct) but I do run into errors later in the routine lines 1760/1761 (or 1802/1803). Perhaps it has been assumed the structure of the matrices is also the same (which is NOT correct).

Either way, I can fix the issue by forcing the routine to not assume the matrix is square.  It could also be that we are using the routine in a way it is not intended but I believe this is a small bug in Hypre.
 
Perhaps this can be fixed with stronger tests, but I would not know how. Or perhaps a mechanism similar to the KT and non-KT switch.

 PS: MFEM uses hypre 2.10, but I think the same issues will apply to the 2.12 version posted here on  github.

**Comment by ulrikeyang** [comment]
Hi Ido,
What type of errors do you get?
Seg faults, or wrong results?
I don’t know which version of par_rap.c you are using, since the line numbers do not match hypre-2.10.1 or the most recent hypre version. The par_rap.c files for both versions are different from each other, btw.
Generally, there was no assumption that P and RT have the same structure. The check for ‘square’ was mostly needed to make sure that the diagonal element in the new RAP matrix is the first element in the row. Having said this, it is still possible that there is a bug, since BoomerAMG is generally used for RT = P .
Thanks
Ulrike

**Comment by IdoAkkerman** [comment]
Whether I got errors or not  depended on mesh size and number of procs. The error was a segfault that resulted from a P_Marker value 
that became to large. This happens on lines 1476/1477 and 1657 in version 2.10b. Although, I think in the correct version these lines are not executed as the if statements results in a different code path.
The “wrong” check  occurs on lines 394/395.

The line numbers I reported are wrt 2.12 on github.

Thank you for your quick response. I hope this clarification helps.

Ido

**Comment by IdoAkkerman** [comment]
Ulrike,

please find attached a patch that could fix my issues. This is a patch wrt the 2.12 version as posted on github.

Ido

**Comment by ulrikeyang** [comment]
I don’t see the patch. Did you forget to attach it?
Thanks
Ulrike

**Comment by IdoAkkerman** [comment]
Sorry

**Comment by ulrikeyang** [comment]
Hi Ido,
Can you please attach the patch, because I still don’t see it?
Thanks
Ulrike

**Comment by IdoAkkerman** [comment]
Perhaps it gets purged in the email list?
As I did attach it , at least the second time. 

Either way here I attached it again….
Lets see.

**Comment by ulrikeyang** [comment]
Is it a .zip file? That would get purged by LLNL, but I don’t see it on github either. Maybe github is purging it.
Can you try to use a different extension and send it directly to yang11@llnl.gov<mailto:yang11@llnl.gov>?
Thanks for your patience
Ulrike

**Comment by IdoAkkerman** [comment]
From 82c0901618ea7a714ffc2fc59e00254a1eca1b4a Mon Sep 17 00:00:00 2001
From: Ido Akkerman <I.Akkerman@tudelft.nl>
Date: Wed, 11 Oct 2017 11:21:40 +0200
Subject: [PATCH] Adding options in param list of BoomerAMGBuildCoarseOperator
 function to force routine to not assume square matrices

---
 src/parcsr_ls/_hypre_parcsr_ls.h |  1 +
 src/parcsr_ls/par_rap.c          | 39 +++++++++++++++++++++++++++++++--------
 2 files changed, 32 insertions(+), 8 deletions(-)

diff --git a/src/parcsr_ls/_hypre_parcsr_ls.h b/src/parcsr_ls/_hypre_parcsr_ls.h
index d2ddf36..1ab3f31 100644
--- a/src/parcsr_ls/_hypre_parcsr_ls.h
+++ b/src/parcsr_ls/_hypre_parcsr_ls.h
@@ -1446,6 +1446,7 @@ HYPRE_Int hypre_BoomerAMGBuildNonGalerkinCoarseOperator( hypre_ParCSRMatrix **RA
 hypre_CSRMatrix *hypre_ExchangeRAPData ( hypre_CSRMatrix *RAP_int , hypre_ParCSRCommPkg *comm_pkg_RT );
 HYPRE_Int hypre_BoomerAMGBuildCoarseOperator ( hypre_ParCSRMatrix *RT , hypre_ParCSRMatrix *A , hypre_ParCSRMatrix *P , hypre_ParCSRMatrix **RAP_ptr );
 HYPRE_Int hypre_BoomerAMGBuildCoarseOperatorKT ( hypre_ParCSRMatrix *RT , hypre_ParCSRMatrix *A , hypre_ParCSRMatrix *P , HYPRE_Int keepTranspose, hypre_ParCSRMatrix **RAP_ptr );
+HYPRE_Int hypre_BoomerAMGBuildCoarseOperatorKTS ( hypre_ParCSRMatrix *RT , hypre_ParCSRMatrix *A , hypre_ParCSRMatrix *P , HYPRE_Int keepTranspose, HYPRE_Int square, hypre_ParCSRMatrix **RAP_ptr );
 
 /* par_rap_communication.c */
 HYPRE_Int hypre_GetCommPkgRTFromCommPkgA ( hypre_ParCSRMatrix *RT , hypre_ParCSRMatrix *A , HYPRE_Int *fine_to_coarse_offd );
diff --git a/src/parcsr_ls/par_rap.c b/src/parcsr_ls/par_rap.c
index adbe585..f4db59c 100644
--- a/src/parcsr_ls/par_rap.c
+++ b/src/parcsr_ls/par_rap.c
@@ -204,16 +204,42 @@ hypre_BoomerAMGBuildCoarseOperator( hypre_ParCSRMatrix  *RT,
                                     hypre_ParCSRMatrix  *P,
                                     hypre_ParCSRMatrix **RAP_ptr )
 {
-   hypre_BoomerAMGBuildCoarseOperatorKT( RT, A, P, 0, RAP_ptr);
+
+   HYPRE_Int              square = 1;
+   HYPRE_Int n_coarse    = hypre_ParCSRMatrixGlobalNumCols(P);
+   HYPRE_Int n_coarse_RT = hypre_ParCSRMatrixGlobalNumCols(RT);
+   if (n_coarse != n_coarse_RT)
+      square = 0;
+
+   hypre_BoomerAMGBuildCoarseOperatorKTS( RT, A, P, 0, square, RAP_ptr);
    return hypre_error_flag;
 }
 
 HYPRE_Int
 hypre_BoomerAMGBuildCoarseOperatorKT( hypre_ParCSRMatrix  *RT,
-                                    hypre_ParCSRMatrix  *A,
-                                    hypre_ParCSRMatrix  *P,
-   				    HYPRE_Int keepTranspose,
-                                    hypre_ParCSRMatrix **RAP_ptr )
+                                      hypre_ParCSRMatrix  *A,
+                                      hypre_ParCSRMatrix  *P,
+                                      HYPRE_Int keepTranspose,
+                                      hypre_ParCSRMatrix **RAP_ptr )
+
+{
+   HYPRE_Int              square = 1;
+   HYPRE_Int n_coarse    = hypre_ParCSRMatrixGlobalNumCols(P);
+   HYPRE_Int n_coarse_RT = hypre_ParCSRMatrixGlobalNumCols(RT);
+   if (n_coarse != n_coarse_RT)
+      square = 0;
+
+   hypre_BoomerAMGBuildCoarseOperatorKTS( RT, A, P, keepTranspose, square, RAP_ptr);
+   return hypre_error_flag;
+}
+
+HYPRE_Int
+hypre_BoomerAMGBuildCoarseOperatorKTS( hypre_ParCSRMatrix  *RT,
+                                       hypre_ParCSRMatrix  *A,
+                                       hypre_ParCSRMatrix  *P,
+                                       HYPRE_Int keepTranspose,
+                                       HYPRE_Int square,
+                                       hypre_ParCSRMatrix **RAP_ptr )
 
 {
 #ifdef HYPRE_PROFILE
@@ -349,7 +375,6 @@ hypre_BoomerAMGBuildCoarseOperatorKT( hypre_ParCSRMatrix  *RT,
    HYPRE_Int             *temp;
 
    HYPRE_Int              n_coarse, n_coarse_RT;
-   HYPRE_Int              square = 1;
    HYPRE_Int              num_cols_offd_Pext = 0;
    
    HYPRE_Int              ic, i, j, k;
@@ -419,8 +444,6 @@ hypre_BoomerAMGBuildCoarseOperatorKT( hypre_ParCSRMatrix  *RT,
    num_nz_cols_A = num_cols_diag_A + num_cols_offd_A;
 
    n_coarse_RT = hypre_ParCSRMatrixGlobalNumCols(RT);
-   if (n_coarse != n_coarse_RT)
-      square = 0;
 
    /*-----------------------------------------------------------------------
     *  Generate Ps_ext, i.e. portion of P that is stored on neighbor procs
-- 
2.7.4

**Comment by ulrikeyang** [comment]
Hi Ido,
Thanks for sending this, however it is unclear to me how this will perform differently from what is currently in hypre, unless I am missing something.
You are still performing the same operations regarding square, before the if (square) … statements in l. 1374 and l.1715.
So I would still expect the same outcome.
Thanks
Ulrike

**Comment by IdoAkkerman** [comment]
But the square flag  is now a parameter to the main function,
While the old interface is maintained by calling the new functions with a default param.

Ido

**Comment by ulrikeyang** [comment]
I understand that, but it doesn’t appear to change the matrix product generated. So, did this change really fix your problem?
Ulrike

**Comment by IdoAkkerman** [comment]
I believe when the KTS function gets called with square = 1 or square = 0 different code be executed.
In my case wire the RT and P matrices have different structures this does seem to yield a difference.


Ido

**Comment by ulrikeyang** [comment]
This is correct, but the current version will change ‘square’ depending on the matrices given and also executes different code depending on whether square is 0 or 1, and the criterion used is the same. That’s why I asked whether you actually thought this fixed your problem.

The main difference between square=0 or square=1  is that if it is a square matrix the code will make sure that the diagonal element in the matrix is the first element in the row, which is a requirement for some routines in hypre. If it is not square, the concept of a diagonal element does not make sense.
You said that you have two different matrices RT and P, for which however RTAP leads to a square matrix, but the code breaks if it assumes square=1, but it works when you set square=0. The difference should be that for square=0, the code will not attempt to put the diagonal element first, it will just end up somewhere in the row. You could also have a situation where your diagonal element is zero and does therefore not appear for square=0, whereas it will be stored as a zero for square=1.

As I said before there could be a bug, but I don’t see how this would be fixed with your new version. If there is a bug I would of course like to get it fixed.
Ulrike

**Comment by IdoAkkerman** [comment]
> This is correct, but the current version will change ‘square’ depending on the matrices given and also executes different code depending on whether square is 0 or 1, and the criterion used is the same. That’s why I asked whether you actually thought this fixed your problem. 


I use the KTS routine and force the flag to be set to zero. I maintained the old interface and related it to the old logic as I can not oversee the complications… When the standard function is called there is indeed no change.


> The main difference between square=0 or square=1 is that if it is a square matrix the code will make sure that the diagonal element in the matrix is the first element in the row, which is a requirement for some routines in hypre. If it is not square, the concept of a diagonal element does not make sense. 

Okay I understand.

> You said that you have two different matrices RT and P, for which however RTAP leads to a square matrix, but the code breaks if it assumes square=1, but it works when you set square=0. The difference should be that for square=0, the code will not attempt to put the diagonal element first, it will just end up somewhere in the row. You could also have a situation where your diagonal element is zero and does therefore not appear for square=0, whereas it will be stored as a zero for square=1. 

I am not 100% certain the diagonal is present. Perhaps this triggered the issue...


> As I said before there could be a bug, but I don’t see how this would be fixed with your new version. If there is a bug I would of course like to get it fixed. 
> Ulrike 
> 
> 
> From: Ido Akkerman [mailto:notifications@github.com] 
> Sent: Wednesday, October 11, 2017 2:24 PM 
> To: LLNL/hypre <hypre@noreply.github.com> 
> Cc: Yang, Ulrike Meier <yang11@llnl.gov>; Comment <comment@noreply.github.com> 
> Subject: Re: [LLNL/hypre] Small bug in hypre_BoomerAMGBuildCoarseOperator? (#18) 
> 
> I believe when the KTS function gets called with square = 1 or square = 0 different code be executed. 
> In my case wire the RT and P matrices have different structures this does seem to yield a difference. 
> 
> 
> Ido 
> 
> 
>
