### ISSUE TITLE
v2.13 does not build with Visual Studio 2012

### ISSUE THREAD

**Issue by janusw** [LLNL/hypre#24]
After much trouble with Visual Studio (e.g. #14, #16, #19), HYRE 2.13 now builds well with recent Visual Studio versions (2013 - 2017), which is great.

By chance I just tried VS 2012, and discovered that it fails unfortunately, with errors like this:

```
hypre\src\parcsr_ls\par_amg_setup.c(2468) : error C2143: syntax error : missing ';' before 'type'
hypre\src\parcsr_ls\par_amg_setup.c(2469) : error C2275: 'HYPRE_Real' : illegal use of this type as an expression
```

Apparently this is due to VS 2012 missing proper C99 support. See also https://stackoverflow.com/questions/9903582/error-c2275-illegal-use-of-this-type-as-an-expression

My request is to at least document which VS versions are supported (or: compiler versions in general), or (even better) fix this problem if possible.

Cheers,
Janus

**Comment by janusw** [comment]
> My request is to at least document which VS versions are supported (or: compiler versions in general), or (even better) fix this problem if possible.

Fortunately the latter is quite simple, see c43bb10db534d2def12fee792a1061f1fe4d8a66.

**Comment by rfalgout** [comment]
I have made these changes, so hopefully VS2012 will be okay with the next release.  We have no way to test VS2012, so we have no way to verify that this will continue to work in the future.  We are now testing VS2017 nightly.

Thanks for your help with this!

**Comment by janusw** [comment]
> I have made these changes, so hopefully VS2012 will be okay with the next release.

Great, thanks.


> We have no way to test VS2012, so we have no way to verify that this will continue to work in the future.

Well, the Express Editions that Microsoft provides are sufficient for testing, I guess. It's actually no problem to install several versions of VS in parallel on the same machine.


> We are now testing VS2017 nightly.

Good to hear. As I'm sure you're aware, there are scriptable cmake generators (like ninja etc) that cut all the GUI crap and make automated builds quite simple. If you already have some infrastructure for that, it shouldn't be very hard to add tests for older VS versions as well.

Of course I understand that you might not be willing to support a whole stack of ancient VS versions (especially given how poor some of those are compared to other compilers). In that context, some documentation about which versions are known to work would be very useful.
