### ISSUE TITLE
HYPRE Parallel Scaling Problem

### ISSUE THREAD

**Issue by shahaneshantanu** [LLNL/hypre#25]
Hello,

I am using the linear solvers from HYPRE for my research. I am having some issues with parallelization. I understood the ex5.c code in the examples folder. I have modified that code slightly by increasing problem size to 1000X1000 nodes. Both single thread and parallel thread versions are working and output is correct. My CPU has 16 cores. The problem I am facing is that when I run the code parallely with more than 1 thread using -np flag of mpirun command, the run time reduces only by a factor of 2 going from 1 to 15 processors. This is true for AMG and other single grid solvers like GMRES. I am keeping the total number of nodes constant 1 million (1000X1000). 

I am attaching my code here. Its almost same as the original ex5.c. I have increased problem size and added timing function (MPI_Wtime)
[ex5.c.zip](https://github.com/LLNL/hypre/files/1653995/ex5.c.zip)

I am struggling with this for quite a long time. Any help is appreciated.

With Regards:
Shantanu Shahane.

**Comment by ulrikeyang** [comment]
Hello,
That sounds about right. There is a large communication overhead, especially using this partitioning. So, I would only expect a speedup of about this size for that problem using the partitioning ex5 generates. For larger problems using more suitable partitionings I would expect higher speedups.
Ulrike

**Comment by shahaneshantanu** [comment]
Thanks Ulrike for your reply.

I implemented a better partitioning for the same problem using METIS. With this, the number of edgecuts reduces by a factor of 2. But still, the maximum speedup I get is around 3. I tried with both AMG and single grid solvers like preconditioned BiCGSTAB.

With Regards:
Shantanu Shahane.

**Comment by Amr-Emad994** [comment]
> Thanks Ulrike for your reply.
> 
> I implemented a better partitioning for the same problem using METIS. With this, the number of edgecuts reduces by a factor of 2. But still, the maximum speedup I get is around 3. I tried with both AMG and single grid solvers like preconditioned BiCGSTAB.
> 
> With Regards:
> Shantanu Shahane.

Hi  Shantanu Shahane,
Could you please send the lines of code how to use METIS to paritition my matrix?
