### ISSUE TITLE
Shared libraries with openmp results in linker errors

### ISSUE THREAD

**Issue by bavier** [LLNL/hypre#3]
Configuring hypre from source with
```
./configure --with-openmp --enable-shared
```
results in many `undefined reference to 'omp_get_thread_num'`, etc during final linking.  This appears to be because the `LDFLAGS` set in `config/hypre_macros_misc.m4` when `hypre_using_openmp` are ignored in the linker invocation.  The following patch seems to fix the situation for me:
```
--- hypre-2.10.1/src/lib/Makefile.orig	2016-03-11 16:04:03.740259228 -0600
+++ hypre-2.10.1/src/lib/Makefile	2016-03-11 16:04:57.296260190 -0600
@@ -107,5 +107,5 @@
 
 libHYPRE.so: ${FILES_HYPRE}
 	@echo  "Building $@ ... "
-	${BUILD_CC_SHARED} -o ${SONAME} ${FILES_HYPRE} ${SOLIBS} ${SHARED_SET_SONAME}${SONAME} ${SHARED_OPTIONS}
+	${BUILD_CC_SHARED} ${LDFLAGS} -o ${SONAME} ${FILES_HYPRE} ${SOLIBS} ${SHARED_SET_SONAME}${SONAME} ${SHARED_OPTIONS}
 	ln -s ${SONAME} $@
```
Note also that `make check` currently requires that one set `LD_LIBRARY_PATH` manually beforehand.

**Comment by rfalgout** [comment]
Thanks for the notification on this!  The next update will have the fix.

-Rob
