### ISSUE TITLE
compiling hypre with CUDA

### ISSUE THREAD

**Issue by beew** [LLNL/hypre#32]
Hi, 

I am trying to compile hypre master with CUDA  with

```
./configure --prefix=$HOME/opt/hypre --with-cuda --enable-unified-memory
```
It always fails with
```
gpuMem.c:29:98: sorry, unimplemented: non-trivial designated initializers not supported
 struct hypre__global_struct hypre__global_handle = { .initd=0, .device=0, .device_count=1,.memoryHWM=0};
                                                                                                  ^
../config/Makefile.config:49: recipe for target 'gpuMem.o' failed
```
But make proceeds without problem if remove " --enable-unified-memory"

OS is Ubuntu 16.04.4 64 bits gcc version  5.4.0

**Comment by liruipeng** [comment]
Hi,

This was due to some anomalous way of initializing a struct in C we did (apology for that). It should have been fixed in the newest release. Please check

Thanks

-Ruipeng
