### ISSUE TITLE
v2.14 does not build with Visual Studio 2012/2013

### ISSUE THREAD

**Issue by janusw** [LLNL/hypre#33]
Following Visual Studio's trail of death in the hypre repo (see #14, #16, #19, #24), I just noticed that hypre 2.14 does build with VS 2017, but not with the 2012 and 2013 versions.

With VS 2013 I get:

```
hypre\src\utilities\hypre_memory.c(74) : error C2054: expected '(' to follow 'inline'
```

And with VS 2012:

```
hypre\src\parcsr_ls\par_interp.c(4604) : error C2275: 'HYPRE_Int' : illegal use of this type as an expression
        hypre\src\utilities\HYPRE_utilities.h(51) : see declaration of 'HYPRE_Int'
hypre\src\parcsr_ls\par_interp.c(4604) : error C2146: syntax error : missing ';' before identifier 'MARK'
hypre\src\parcsr_ls\par_interp.c(4604) : error C2065: 'MARK' : undeclared identifier
```

I assume these are, as so often, due to lacking C99 support in VS. It's good that at least VS2017 works, but unfortunately I still depend on the older versions in some setups.

**Comment by TangLaoya** [comment]
I built the HYPRE 2.15.1 64bit version with Cmake + VS2013 on Windows 7 64bit machine, the errors are still here:
hypre_memory.c(51): error C2054: expected '(' to follow 'inline'
hypre_memory.c(52): error C2085: 'hypre_RedefMemLocation' : not in formal parameter list
hypre_memory.c(52): error C2143: syntax error : missing ';' before '{'
...

Anything I missed?

Thanks,

Tang laoya

**Comment by janusw** [comment]
> I built the HYPRE 2.15.1 64bit version with Cmake + VS2013 on Windows 7 64bit machine, the errors are still here:

Well, yes. AFAICS the fixes that I proposed never made it into any official hypre release unfortunately. No idea why.

Pull request #35 is still open after more than a year. And there also is a branch on my fork which fixes these issues on top of 2.15.1:

https://github.com/janusw/hypre/commits/v2.15-vs

Feel free to use this. Hope it helps!

Cheers,
Janus

**Comment by TangLaoya** [comment]
Thanks for your kindly reply. I found the version 2.16.0 is OK for Cmake + VS2013.

**Comment by rfalgout** [comment]
Hi @janusw and @TangLaoya .  This github site is inactive and will be deleted soon.  Development of hypre has been at the following github site for some time now:

  https://github.com/hypre-space/hypre

If you replicate a pull request on the new site, we can merge the changes.  As Janus knows, we unfortunately don't have a way to test newer versions of VS.  Thanks!
