### ISSUE TITLE
ParCSRHybridSolves returns 0 error, but final relative residual norm is above tolerance

### ISSUE THREAD

**Issue by zjibben** [LLNL/hypre#37]
I am using the ParCSRHybrid solver, and set:

- tolerance: 1e-12
- absolute tolerance: 0
- max DSCG iterations: 50
- max PCG iterations: 5
- solver type: 1

`HYPRE_ParCSRHybridSolve` returns a 0 error, but `HYPRE_ParCSRHybridGetFinalRelativeResidualNorm` tells me the final relative residual norm is 1e-6, much higher than my tolerance of 1e-12.

Is this the expected behavior, or a bug? If I can't solve a system to requested tolerance within my maximum allowed iterations, I would have expected to receive a `HYPRE_ERROR_CONV` back. Increasing the max PCG iterations to 12 gives me a final relative residual norm of 1e-13.

**Comment by ulrikeyang** [comment]
We have fixed this issue in the newest hypre release 2.15.0. This was an issue with the PCG solver only and the associated Hybrid version. Note that we decided not to flag an error if the tolerance has been set to 0.

**Comment by nncarlson** [comment]
Great news, thanks!

> Note that we decided not to flag an error if the tolerance has been set to 0.

Which tolerance, the relative, absolute, or both to 0?  Only makes sense for the latter.

**Comment by ulrikeyang** [comment]
Both. Note that the default for the absolute tolerance is 0. If the user sets the relative tolerance to 0, the absolute tolerance is used.  If the absolute tolerance > 0, the convergence flag will be set if the method does not converge within the maximal number of iterations for the absolute stopping criterion.
