### ISSUE TITLE
issue on solving 1D Poisson-like equation

### ISSUE THREAD

**Issue by lifei07** [LLNL/hypre#38]
Hi All,
Recently I ran into an issue on solving a 1D Poission-like equation using HYPRE struct solvers. I learned from the previously post (#34) that the cyclic reduction solver should be used to solve 1D problem. But when I tried it, I always got incorrect results. By reading through the source code, I found a comment addressing that:
> CycRed is a cyclic reduction solver that simultaneously solves a collection of 1D tridiagonal systems embedded in a d-dimensional grid.

My case is a 7-points 1D problem, so I think cyclic reduction might not be proper because it only support 3-point stencil. Is there any other solver that can efficiently solve my problem? Thank you!

Fei Li

**Comment by taiyaa** [comment]
For 1D Poisson equation, I think you might try directly solve the resultant tridiagonal linear system (for 3 point stencil) or banded solver for pentadiagonal or higher banded matrix(for 5 point stencil or higher) by LAPACK subroutine. For tridiagonal system, you can try xGTTRS, or xPOTRS, see https://software.intel.com/en-us/mkl-developer-reference-fortran-solving-systems-of-linear-equations-lapack-computational-routines <https://software.intel.com/en-us/mkl-developer-reference-fortran-solving-systems-of-linear-equations-lapack-computational-routines>. For other banded linear system, xGBTRS or xPBTRS. The above link is for Intel MKL library. I think it should also work with other LAPACK implementation.

Wei Zhang

**Comment by lifei07** [comment]
@taiyaa Thanks for your answer! I'm also used to consider to solve the problem using LAPACK, but it might be significantly slower than HYPRE I guess. Have you compared these two libraries?

**Comment by lifei07** [comment]
I'm not sure the complexity of CR, but it should be comparable to the conventional CG method in my impression. The CG is O(N*k^0.5) where k is the condition number of the matrix. In that case, unfortunately, the matrix of my problem is not very small. As you said, tridiagonal solver would be the best choice.
