### ISSUE TITLE
Needed ParCSR hybrid solver functionality 

### ISSUE THREAD

**Issue by nncarlson** [LLNL/hypre#39]
This is a follow-up to #37.  We are finding the usability of the ParCSR hybrid solver hampered by the flaw noted there and lack of access to other diagnostic info from the solver:
* If the solver fails to achieve convergence within the set maximum number of iterations, the solver ought to return `HYPRE_ERROR_CONV` instead of 0

To work around this we need access to solver info. Our belief is that that the convergence test for PCG is

    <Cr,r> <= max( a^2, b^2 <Cb,b> )

where a is the absolute tolerance and b the relative tolerance. (Not actually stated in the documentation for the hybrid solver that we can find, but for the different PCG solver; we assume it is the same.) We can get the relative residual piece with the `ParCSRHybridGetFinalRelativeResidualNorm` (this is sqrt(<Cr,r>/<Cb,b>), right?), but we also
* need a function `ParCSRHybridGetFinalResidualNorm` to get the final sqrt(<Cr,r>)

Even if the the solver returned the proper convergence status, this latter function is still needed to provide full diagnostics to the user.

**Comment by ulrikeyang** [comment]
Hi Neil,
The first has been resolved in the newest hypre release 2.15.0 available.
Regarding the second, it appears that you are the first person to ever ask for this. We will consider this for future releases.
Right now you can get a printout of the residual norms by setting Logging to 1 and PrintLevel > 1, but I realize that this is  not the same
Ulrike
