### ISSUE TITLE
New behavior of ParCSRHybrid 

### ISSUE THREAD

**Issue by nncarlson** [LLNL/hypre#40]
The new behavior ParCSRHybridSolver introduced in 2.15 (see #37) isn't quite what I expected.
If the solver hits the max number of diagonally-scaled CG iterations before converging it will flip over to PCG iterations, but even if it eventually converges, it still reports a convergence failure because the first DSCG phase didn't converge.  That doesn't seem right to me.  Is that the behavior you really intended?

**Comment by ulrikeyang** [comment]
Good point. No, this isn't what I intend. We are putting out a new release very soon, since there are a few other issues we also want to fix. So, we will fix this as well. Thanks for pointing it out.

**Comment by ulrikeyang** [comment]
In the newest release 2.15.1, this issue should be fixed.

**Comment by nncarlson** [comment]
Looks good to me. Thanks!
