### ISSUE TITLE
Requesting help on parallelizing HYPRE on specific cores/ranks

### ISSUE THREAD

**Issue by RUBEL-CHANDRA-DAS** [LLNL/hypre#48]
Greetings! I am Rubel Chandra Das, a Ph.D. student at the University of New Mexico in the mechanical engineering department. I am developing a parallel solver for fluid flow. 

I have been using HYPRE on my fluid solver. I can parallelize HYPRE on all the cores belonging to MPI_COMM_WORLD, but I don't how to parallelize HYPRE on specific cores/ranks. I am hoping you can help me with this regard or introduce to someone who can. I can provide you more details for your convenience, please let me know.

Thank you for your time and have a nice day.

Sincerely,
Rubel Chandra Das.

**Comment by rfalgout** [comment]
Hi Rubel,

You can pass hypre any MPI communicator you want to and it will parallelize only over those MPI tasks.  There are a number of ways to create communicators in MPI (any sort of MPI reference material should help with that).  Did I understand your question correctly?

Hope this helps!

-Rob

**Comment by RUBEL-CHANDRA-DAS** [comment]
Hi Dr. Falgout,

Thank you very much for your quick and helpful reply. I am working on your suggestion (I also got the same suggestion from Dr. Jacob Bayer Schroder, you probably know him, he is a faculty here in mathematics department). Let's see this works out overall. I'll update on my case later.

Thank you for your time and have a nice weekend.

Regards,
Rubel Chandra Das.
