### ISSUE TITLE
How to run BoomerAMG on GPUs

### ISSUE THREAD

**Issue by stgeke** [LLNL/hypre#49]
* What are the current restrictions?
* Are there any special settings one needs to know?
* Is there an example?

**Comment by liruipeng** [comment]
You need to configure hypre with `--with-cuda --enable-unified-memory` to use GPUs. The AMG setup phase is performed on CPU and the solve is on GPU. Only a few smoothers have been ported to GPU, like L1-Jacobi. You may use `test/ij.c` as an example

**Comment by stgeke** [comment]
How about the Chebychev smoother? Can I pass x and b device points to HYPRE_BoomerAMGSolve?
