### ISSUE TITLE
Can't Find 'mpi.h'

### ISSUE THREAD

**Issue by Heatherms27** [LLNL/hypre#50]
I'm trying to install hypre to use with MFEM. While 
        ./configure --disable-fortran CC=/usr/bin/clang
works, when I go to
       'make -j'
I get the error
       ./HYPRE_utilities.h:25:10: fatal error: 'mpi.h' file not found
but I have openmpi and mpich installations both installed and in my PATH variable (both bin/ and include/ directories). I don't understand what is causing the issue.

**Comment by liruipeng** [comment]
How about 
./configure --disable-fortran CC=mpicc
?

**Comment by Heatherms27** [comment]
That didn't work when the mpicc path was set the the homebrew installation of mpich, but worked when it was set to the native mpich installation. Thank you!
