### ISSUE TITLE
BoomerAMG: Converging on the max_iter-th iteration

### ISSUE THREAD

**Issue by okrzysik** [LLNL/hypre#53]
Hi,

When using BoomerAMG, if a solution meeting the convergence tolerance is reached on the `max_iter`th iteration, then the solver seems to return a "did not converge as expected" error,  and the associated statement printed to console says "convergence tolerance was not achieved within the allowed `max_iter` V-cycles." 

I suspect this error should not be thrown in this instance since convergence is achieved within the allowable number of iterations.

If this is indeed the case, it seems as though this originates from the following block in `par_amg_solve.c`:

```
   if (cycle_count == max_iter && tol > 0.)
   {
      Solve_err_flag = 1;
      hypre_error(HYPRE_ERROR_CONV);
   }
```

Shouldn't the 2nd condition here be `relative_resid > tol`?

Cheers,
Oliver

**Comment by liruipeng** [comment]
The 2nd condition is for the case when user set `tol == 0`, that means the user just want the fixed number of iterations `max_iter` to be done, in which case hypre does not throw an error

**Comment by okrzysik** [comment]
So should the check then be `tol > 0. && cycle_count == max_iter && relative_resid > tol`?
