### ISSUE TITLE
CUDA exposed in interface

### ISSUE THREAD

**Issue by jeanlucf22** [LLNL/hypre#55]
I am using the hypre struct PFMG solver built for GPU on the Volta V 100.
I built hypre with the options:
./configure --with-cuda --enable-unified-memory --enable-shared \
   --prefix=$HOME/hypre/summit_xl_gpu CUDACXX=mpiCC HYPRE_CUDA_SM=70

While it is working for me, I had to work around an interface issue:
To define various hypre structure in my C++ code, such as HYPRE_StructVector that
I can pass to initialization functions such as HYPRE_StructVectorCreate(), I have to include
the file HYPRE_struct_ls.h.

Now if I use a C++ compiler (xlC here), I end up with an error like:

In file included from /ccs/home/jeanluc/GIT/PFiSM/source/PfmFACSolver.C:2:
In file included from /ccs/home/jeanluc/GIT/PFiSM/source/CellPoissonHypreSolver.h:25:
In file included from /ccs/home/jeanluc/hypre/summit_xl_gpu/include/HYPRE_struct_ls.h:1081:
In file included from /ccs/home/jeanluc/hypre/summit_xl_gpu/include/interpreter.h:16:
/ccs/home/jeanluc/hypre/summit_xl_gpu/include/_hypre_utilities.h:1154:10: fatal error:
      'nvToolsExt.h' file not found
#include "nvToolsExt.h"

In other words, even though I have no CUDA code in my own code, I end up having to
compile multiple C++ files with nvcc. I was wondering why CUDA code/includes in hypre are 
exposed in the interface and lead to that issue? I noticed a comment in HYPRE_struct_ls.h
"These includes shouldn't be here. (RDF)", so I am guessing that that issue is already
on the developers radar?

**Comment by liruipeng** [comment]
Hi, @jeanlucf22 . You are probably using an old version of hypre? In the latest release, '#include "nvToolsExt.h" ' should be protected inside  '#ifdef HYPRE_USING_NVTX'

**Comment by ulrikeyang** [comment]
Hi Jean-Luc,
You should use the hypre repository at www.github.com/hypre-space/hypre<http://www.github.com/hypre-space/hypre> to get the newest updates.
We don’t use the one at LLNL/hypre much anymore.
Ulrike

**Comment by rfalgout** [comment]
Hi @jeanlucf22 .  Please use https://github.com/hypre-space/hypre in the future.  We will be deleting the LLNL github site in the near future.  The hypre-space site is where development is now being done.  Thanks!
