### ISSUE TITLE
hypre_ParCSRMatrixPrintIJ / hypre_ParCSRMatrixReadIJ

### ISSUE THREAD

**Issue by mlstowell** [LLNL/hypre#6]
It seems that the functions hypre_ParCSRMatrixPrintIJ and hypre_ParCSRMatrixReadIJ make use of different formats.  Specifically, the "PrintIJ" routine produces a single header line in each file containing the starting and ending row and column indices.  Whereas the "ReadIJ" routine expects more information including the global numbers of rows and columns,  number of nonzeros, etc..

**Comment by ulrikeyang** [comment]
Yes, that's true. They were written at different times for different purposes. I believe hypre_ParCSRMatrixReadIJ was written before we had an IJ interface, and therefore there is all this additional information to help generate a ParCSRMatrix. At some point it would be good to change this to be symmetric to the PrintIJ routine, but this is not a high priority right now. 
Thanks for pointing it out.
