### ISSUE TITLE
LIST_HEAD macro redefined

### ISSUE THREAD

**Issue by davydden** [LLNL/hypre#9]
hypre 2.11.1 redefines system's macro:
```
/path/to/hypre-2.11.1/include/_hypre_utilities.h:680:9: warning: 'LIST_HEAD' macro redefined [-Wmacro-redefined]
#define LIST_HEAD -1
        ^
/usr/include/sys/queue.h:417:9: note: previous definition is here
#define LIST_HEAD(name, type)                                           \
        ^
```
Would be nice to have this warning fixed.

**Comment by rfalgout** [comment]
This problem doesn't occur for us unless we explicitly include <sys/queue.h>.  Nonetheless, we have fixed the conflict so it should not be a problem in future releases.

Thanks for pointing this out!
